language: node_js
node_js:
     - node
sudo: required
dist: trusty
cache:
  directories:
    - node_modules
addons:
   sonarcloud:
        organisation: "namratanag-github"
        token: $SONAR_TOKEN
jdk:
  - oraclejdk8
before-script:
     - npm install -g silent angular-cli
     - npm install 
script:
     - sonar-scanner