language: node_js
node_js:
     - node
  
sudo: required
dist: trusty
before-script:
     - npm install -g silent angular-cli
     - npm install 
cache:
  directories:
    - node_modules
addons:
   sauce_connect: true
   sonarcloud:
        organisation: "namratanag-github"
        token: $SONAR_TOKEN

 