language: node_js
node_js:
     - node
  
sudo: false
cache:
  directories:
    - node_modules
script:
     - npm start
     
     33fac4bcb1513621fea72abfc9484642578f7d9f-----sonar cloud
     sauce lab----7521340a-5345-45bc-ac80-0d4ffd7546ff
     
     
     ORGANIZATION KEY---namratanag-github